import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('lang');
    return (saved === 'en' || saved === 'ar') ? saved : 'ar';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('lang', lang);
  };

  // Apply RTL/LTR to document
  useEffect(() => {
    document.body.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation function
export const translations = {
  en: {
    // Auth
    login: "Login",
    signup: "Sign Up",
    email: "Email",
    password: "Password",
    name: "Name",
    confirmPassword: "Confirm Password",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    switchToLogin: "Login",
    switchToSignup: "Sign Up",
    signingIn: "Signing you in...",
    creatingAccount: "Creating your account...",
    continueJourney: "Continue your chemistry journey",
    startJourney: "Start your chemistry journey today",
    passwordsDoNotMatch: "Passwords do not match",
    passwordTooShort: "Password must be at least 6 characters",
    failedLogin: "Failed to login. Please try again.",
    noAccountFound: "No account found with this email. Please sign up first.",
    incorrectPassword: "Incorrect password. Please try again.",
    invalidCredentials: "Invalid email or password. Please check and try again.",
    tooManyAttempts: "Too many failed attempts. Please try again later.",
    failedCreateAccount: "Failed to create account. Please try again.",
    
    // Profile
    profile: "Profile",
    leaderboard: "Leaderboard",
    appearance: "Appearance",
    language: "Language",
    logout: "Logout",
    theme: "Theme",
    dark: "Dark",
    light: "Light",
    selectAvatar: "Select Avatar",
    avatar: "Avatar",
    
    // Stats
    level: "Level",
    xp: "XP",
    lessons: "Lessons",
    courses: "Courses",
    progress: "Progress",
    maxLevel: "Max Level",
    completed: "Completed",
    bronze: "Bronze",
    silver: "Silver",
    gold: "Gold",
    platinum: "Platinum",
    crystal: "Crystal",
    you: "You",
    noUsersOnLeaderboard: "No users on the leaderboard yet",
    
    // Main Navigation
    elements: "Elements",
    coursesTab: "Courses",
    search: "Search",
    quiz: "Quiz",
    
    // Elements Screen
    exploreElements: "Explore the building blocks of the universe.",
    all: "All",
    alkaliMetal: "Alkali Metals",
    alkalineEarthMetal: "Alkaline Earth Metals",
    transitionMetal: "Transition Metals",
    postTransitionMetal: "Post-Transition Metals",
    metalloid: "Metalloids",
    nonmetal: "Nonmetals",
    halogen: "Halogens",
    nobleGas: "Noble Gases",
    lanthanide: "Lanthanides",
    actinide: "Actinides",
    mass: "Mass",
    physicalState: "Physical State",
    didYouKnow: "Did you know?",
    atomicMass: "Atomic Mass",
    state: "State",
    density: "Density",
    discoveredBy: "Discovered By",
    meltingPoint: "Melting Point",
    boilingPoint: "Boiling Point",
    config: "Config",
    shells: "Shells",
    testYourKnowledge: "Test your knowledge with 20 questions per course.",
    
    // Search
    searchElements: "Search elements...",
    trending: "Trending",
    recentSearches: "Recent Searches",
    noRecentSearches: "No recent searches yet. Search for elements to see them here!",
    
    // Courses
    masterArchitecture: "Master the architecture of matter through our learning modules.",
    backToCourses: "Back to Courses",
    free: "Free",
    comingSoon: "Coming soon",
    backToQuizzes: "Back to Quizzes",
    questions: "Questions",
    testYourKnowledgeShort: "Test Your Knowledge",
    quizDescription: "This quiz evaluates what you have learned in the",
    quizDescription2: "course. It contains 20 multiple-choice questions covering all key concepts.",
    startQuiz: "Start Quiz",
    historyResults: "History Results",
    noQuizAttempts: "You haven't attempted this quiz yet.",
    
    // Lesson
    lesson: "Lesson",
    completedLesson: "Completed",
    quickQuiz: "Quick Quiz",
    watchVideo: "Watch Video",
    tryAgainLesson: "Try again",
    retryWithNewQuestion: "Retry with New Question",
    submitAnswer: "Submit Answer",
    nextLesson: "Next Lesson",
    answerQuestionToUnlock: "Answer the question to unlock",
    completeQuizToContinue: "Complete the quiz above to continue",
    
    // Quiz
    question: "Question",
    exit: "Exit",
    next: "Next",
    finish: "Finish",
    correct: "Correct",
    incorrect: "Incorrect",
    score: "Score",
    of: "of",
    correctWellDone: "Correct! Well done.",
    incorrectAnswer: "Incorrect. The correct answer is shown above.",
    nextQuestion: "Next Question",
    finishQuiz: "Finish Quiz",
    yourScore: "Your Score",
    congratulations: "Congratulations!",
    greatJob: "Great job!",
    keepTrying: "Keep trying!",
    tryAgain: "Try Again",
    backToQuiz: "Back to Quiz",
    outstanding: "Outstanding! Excellent work!",
    greatJobWellDone: "Great job! Well done!",
    goodEffort: "Good effort! Keep practicing!",
    keepStudying: "Keep studying! You can do better!",
    answeredCorrectly: "You answered {score} out of {total} questions correctly.",
    backToQuizIntro: "Back to Quiz Intro",
    
    // Leaderboard
    leaderboardTitle: "Leaderboard",
    rank: "Rank",
    
    // Welcome
    welcome: "Welcome",
    start: "Start",
    accountRequired: "Account Required",
    accountRequiredMessage: "To access courses and quizzes you need a free account",
    close: "Close",
    ok: "OK",
    loggedOutSuccess: "You are logged out successfully",
    signInToTrackProgress: "Sign in to track your progress",
    signIn: "Sign In",

    // App / UI misc
    appTitle: "Chemistry Beacon",
    sortByCategory: "Sort by Category",
    sortByAtomicNumber: "Sort by Atomic Number",
    na: "N/A",

    // States (Elements)
    solid: "Solid",
    liquid: "Liquid",
    gas: "Gas",
    unknown: "Unknown",

    // Element names (symbol -> localized name)
    elementNames: {},

    // "Did you know?" facts per element symbol
    didYouKnowFacts: {},
    
    // Category Labels
    atomicNo: "Atomic No.",
  },
  
  ar: {
    // Auth
    login: "تسجيل الدخول",
    signup: "إنشاء حساب",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    name: "الاسم",
    confirmPassword: "تأكيد كلمة المرور",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    dontHaveAccount: "ليس لديك حساب؟",
    switchToLogin: "تسجيل الدخول",
    switchToSignup: "إنشاء حساب",
    signingIn: "جاري تسجيل الدخول...",
    creatingAccount: "جاري إنشاء الحساب...",
    continueJourney: "تابع رحلتك في الكيمياء",
    startJourney: "ابدأ رحلتك في الكيمياء اليوم",
    passwordsDoNotMatch: "كلمات المرور غير متطابقة",
    passwordTooShort: "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
    failedLogin: "فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.",
    noAccountFound: "لم يتم العثور على حساب بهذا البريد الإلكتروني. يرجى إنشاء حساب أولاً.",
    incorrectPassword: "كلمة المرور غير صحيحة. يرجى المحاولة مرة أخرى.",
    invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة. يرجى التحقق والمحاولة مرة أخرى.",
    tooManyAttempts: "محاولات فاشلة كثيرة جداً. يرجى المحاولة مرة أخرى لاحقاً.",
    failedCreateAccount: "فشل إنشاء الحساب. يرجى المحاولة مرة أخرى.",
    
    // Profile
    profile: "الملف الشخصي",
    leaderboard: "لوحة الصدارة",
    appearance: "المظهر",
    language: "اللغة",
    logout: "تسجيل الخروج",
    theme: "المظهر",
    dark: "داكن",
    light: "فاتح",
    selectAvatar: "اختر الصورة الرمزية",
    avatar: "الصورة الرمزية",
    
    // Stats
    level: "المستوى",
    xp: "نقاط الخبرة",
    lessons: "الدروس",
    courses: "الدورات",
    progress: "التقدم",
    maxLevel: "المستوى الأقصى",
    completed: "مكتمل",
    bronze: "برونزي",
    silver: "فضي",
    gold: "ذهبي",
    platinum: "بلاتيني",
    crystal: "كريستال",
    you: "أنت",
    noUsersOnLeaderboard: "لا يوجد مستخدمون في المتصدرين بعد",
    
    // Main Navigation
    elements: "العناصر",
    coursesTab: "الدورات",
    search: "البحث",
    quiz: "اختبار",
    
    // Elements Screen
    exploreElements: "استكشف لبنات الكون الأساسية.",
    all: "الكل",
    alkaliMetal: "فلزات قلوية",
    alkalineEarthMetal: "فلزات قلوية ترابية",
    transitionMetal: "فلزات انتقالية",
    postTransitionMetal: "فلزات ما بعد انتقالية",
    metalloid: "أشباه الفلزات",
    nonmetal: "لافلزات",
    halogen: "هالوجينات",
    nobleGas: "غازات نبيلة",
    lanthanide: "لانثانيدات",
    actinide: "أكتينيدات",
    mass: "الكتلة",
    physicalState: "الحالة الفيزيائية",
    didYouKnow: "هل تعلم؟",
    atomicMass: "الكتلة الذرية",
    state: "الحالة",
    density: "الكثافة",
    discoveredBy: "اكتشف بواسطة",
    meltingPoint: "نقطة الانصهار",
    boilingPoint: "نقطة الغليان",
    config: "الإعداد",
    shells: "الطبقات",
    testYourKnowledge: "اختبر معرفتك بـ 20 سؤالاً لكل دورة.",
    
    // Search
    searchElements: "ابحث عن العناصر...",
    trending: "الرائج",
    recentSearches: "عمليات البحث الأخيرة",
    noRecentSearches: "لا توجد عمليات بحث حديثة. ابحث عن العناصر لرؤيتها هنا!",
    
    // Courses
    masterArchitecture: "أتقن بنية المادة من خلال وحدات التعلم الخاصة بنا.",
    backToCourses: "العودة إلى الدورات",
    free: "مجاني",
    comingSoon: "قريباً",
    backToQuizzes: "العودة إلى الاختبارات",
    questions: "أسئلة",
    testYourKnowledgeShort: "اختبر معرفتك",
    quizDescription: "يقيّم هذا الاختبار ما تعلمته في دورة",
    quizDescription2: ". يحتوي على 20 سؤال من متعدد الخيارات يغطي جميع المفاهيم الأساسية.",
    startQuiz: "ابدأ الاختبار",
    historyResults: "نتائج السجل",
    noQuizAttempts: "لم تحاول هذا الاختبار بعد.",
    
    // Lesson
    lesson: "درس",
    completedLesson: "مكتمل",
    quickQuiz: "اختبار سريع",
    watchVideo: "شاهد الفيديو",
    tryAgainLesson: "حاول مرة أخرى",
    retryWithNewQuestion: "إعادة المحاولة بسؤال جديد",
    submitAnswer: "إرسال الإجابة",
    nextLesson: "الدرس التالي",
    answerQuestionToUnlock: "أجب على السؤال لإلغاء القفل",
    completeQuizToContinue: "أكمل الاختبار أعلاه للمتابعة",
    
    // Quiz
    question: "سؤال",
    exit: "خروج",
    next: "التالي",
    finish: "إنهاء",
    correct: "صحيح",
    incorrect: "خطأ",
    score: "النتيجة",
    of: "من",
    correctWellDone: "صحيح! أحسنت.",
    incorrectAnswer: "خطأ. الإجابة الصحيحة معروضة أعلاه.",
    nextQuestion: "السؤال التالي",
    finishQuiz: "إنهاء الاختبار",
    yourScore: "نتيجتك",
    congratulations: "تهانينا!",
    greatJob: "عمل رائع!",
    keepTrying: "استمر في المحاولة!",
    tryAgain: "حاول مرة أخرى",
    backToQuiz: "العودة إلى الاختبار",
    outstanding: "ممتاز! عمل ممتاز!",
    greatJobWellDone: "عمل رائع! أحسنت!",
    goodEffort: "جيد! استمر في التدرب!",
    keepStudying: "استمر في الدراسة! يمكنك أن تؤدي بشكل أفضل!",
    answeredCorrectly: "أجبت بشكل صحيح على {score} من أصل {total} أسئلة.",
    backToQuizIntro: "العودة إلى مقدمة الاختبار",
    
    // Leaderboard
    leaderboardTitle: "لوحة الصدارة",
    rank: "الترتيب",
    
    // Welcome
    welcome: "أهلاً وسهلاً",
    start: "ابدأ",
    accountRequired: "يجب إنشاء حساب",
    accountRequiredMessage: "للوصول إلى الدروس والاختبارات يجب إنشاء حساب مجاني",
    close: "إغلاق",
    ok: "حسناً",
    loggedOutSuccess: "تم تسجيل الخروج بنجاح",
    signInToTrackProgress: "سجّل دخولك لتتبع تقدمك",
    signIn: "تسجيل الدخول",

    // App / UI misc
    appTitle: "منارة الكيمياء",
    sortByCategory: "الفرز حسب الفئة",
    sortByAtomicNumber: "الفرز حسب العدد الذري",
    na: "غير متوفر",

    // States (Elements)
    solid: "صلب",
    liquid: "سائل",
    gas: "غاز",
    unknown: "غير معروف",

    // Element names (symbol -> localized name)
    elementNames: {
      "Ac": "أكتينيوم",
      "Ag": "فضة",
      "Al": "ألومنيوم",
      "Am": "أمريكيوم",
      "Ar": "أرغون",
      "As": "زرنيخ",
      "At": "أستاتين",
      "Au": "ذهب",
      "B": "بورون",
      "Ba": "باريوم",
      "Be": "بيريليوم",
      "Bh": "بوريوم",
      "Bi": "بزموت",
      "Bk": "بركليوم",
      "Br": "بروم",
      "C": "كربون",
      "Ca": "كالسيوم",
      "Cd": "كادميوم",
      "Ce": "سيريوم",
      "Cf": "كاليفورنيوم",
      "Cl": "كلور",
      "Cm": "كوريوم",
      "Cn": "كوبرنيسيوم",
      "Co": "كوبالت",
      "Cr": "كروم",
      "Cs": "سيزيوم",
      "Cu": "نحاس",
      "Db": "دوبنيوم",
      "Ds": "دارمشتاتيوم",
      "Dy": "ديسبروسيوم",
      "Er": "إربيوم",
      "Es": "أينشتاينيوم",
      "Eu": "يوروبيوم",
      "F": "فلور",
      "Fe": "حديد",
      "Fl": "فليروفيوم",
      "Fm": "فرميوم",
      "Fr": "فرانسيوم",
      "Ga": "غاليوم",
      "Gd": "غادولينيوم",
      "Ge": "جرمانيوم",
      "H": "هيدروجين",
      "He": "هيليوم",
      "Hf": "هافنيوم",
      "Hg": "زئبق",
      "Ho": "هولميوم",
      "Hs": "هاسيوم",
      "I": "يود",
      "In": "إنديوم",
      "Ir": "إريديوم",
      "K": "بوتاسيوم",
      "Kr": "كريبتون",
      "La": "لانثانوم",
      "Li": "ليثيوم",
      "Lr": "لورنسيوم",
      "Lu": "لوتيتيوم",
      "Lv": "ليفرموريوم",
      "Mc": "موسكوفيوم",
      "Md": "مندليفيوم",
      "Mg": "ماغنسيوم",
      "Mn": "منغنيز",
      "Mo": "موليبدنوم",
      "Mt": "مايتنريوم",
      "N": "نيتروجين",
      "Na": "صوديوم",
      "Nb": "نيوبيوم",
      "Nd": "نيوديميوم",
      "Ne": "نيون",
      "Nh": "نيهونيوم",
      "Ni": "نيكل",
      "No": "نوبليوم",
      "Np": "نبتونيوم",
      "O": "أكسجين",
      "Og": "أوغانيسون",
      "Os": "أوزميوم",
      "P": "فوسفور",
      "Pa": "بروتكتينيوم",
      "Pb": "رصاص",
      "Pd": "بالاديوم",
      "Pm": "بروميثيوم",
      "Po": "بولونيوم",
      "Pr": "براسيوديميوم",
      "Pt": "بلاتين",
      "Pu": "بلوتونيوم",
      "Ra": "راديوم",
      "Rb": "روبيديوم",
      "Re": "رينيوم",
      "Rf": "رذرفورديوم",
      "Rg": "رونتجينيوم",
      "Rh": "روديوم",
      "Rn": "رادون",
      "Ru": "روثينيوم",
      "S": "كبريت",
      "Sb": "إثمد",
      "Sc": "سكانديوم",
      "Se": "سيلينيوم",
      "Sg": "سيبورجيوم",
      "Si": "سيليكون",
      "Sm": "ساماريوم",
      "Sn": "قصدير",
      "Sr": "سترونتيوم",
      "Ta": "تانتالوم",
      "Tb": "تيربيوم",
      "Tc": "تكنيشيوم",
      "Te": "تيلوريوم",
      "Th": "ثوريوم",
      "Ti": "تيتانيوم",
      "Tl": "ثاليوم",
      "Tm": "ثوليوم",
      "Ts": "تينيسين",
      "U": "يورانيوم",
      "V": "فاناديوم",
      "W": "تنغستن",
      "Xe": "زينون",
      "Y": "إتريوم",
      "Yb": "إتيربيوم",
      "Zn": "زنك",
      "Zr": "زركونيوم"
    },

    // "هل تعلم؟" حقائق مختصرة لكل عنصر (حسب رمز العنصر)
    didYouKnowFacts: {
      "Ac": "عنصر مشع نادر، يستخدم في الأبحاث ومصادر النيوترونات.",
      "Ag": "معدن نفيس، موصل للكهرباء، يُستخدم في صناعة العملات المعدنية والتصوير الفوتوغرافي",
      "Al": "معدن خفيف، مقاوم للتآكل، يُستخدم على نطاق واسع في التعبئة والتغليف",
      "Am": "يُستخدم في كاشفات الدخان، وهو عنصر مشع، اكتُشف عام 1944، وهو عنصر اصطناعي",
      "Ar": "غاز نبيل، خامد، يحمي أقواس اللحام، يملأ المصابيح الكهربائية",
      "As": "شبه فلز سام، استُخدم تاريخياً في السموم وأشباه الموصلات.",
      "At": "هالوجين مشع نادر جداً، قد يفيد في علاج السرطان.",
      "Au": "معدن نفيس لا يصدأ، موصل ممتاز، يستخدم في الإلكترونيات.",
      "B": "ضروري للنباتات، يقوي الزجاج، موجود في المنظفات",
      "Ba": "يُستخدم في التصوير الطبي والألعاب النارية، وهو سام في المركبات القابلة للذوبان",
      "Be": "قوي وخفيف الوزن، يستخدم في الفضاء الجوي، سام عند الاستنشاق",
      "Bh": "عنصر اصطناعي مشع، سُمي على اسم بور، اكتُشف عام 1981",
      "Bi": "معدن ثقيل منخفض السمية، يذوب بسهولة، يستخدم في الأدوية.",
      "Bk": "عنصر اصطناعي ومشع، اكتُشف عام 1949، ويُستخدم في الأبحاث فقط",
      "Br": "هالوجين سائل أحمر، سام، يُستخدم في مثبطات اللهب.",
      "C": "أساس الحياة، الماسات، الجرافيت، عنصر متعدد الروابط",
      "Ca": "يبني العظام والقشور والحجر الجيري، ضروري لانقباض العضلات",
      "Cd": "معدن سام، يُستخدم في صناعة البطاريات والأصباغ والقضبان النووية",
      "Ce": "عنصر أرضي نادر وفير، يُستخدم في تلميع الزجاج والمحولات الحفزية",
      "Cf": "عنصر مشع، باعث للنيوترونات، يستخدم في التعدين، تم اكتشافه عام 1950",
      "Cl": "يعقم الماء، غاز سام، يُكوّن ملح الطعام مع الصوديوم",
      "Cm": "عنصر مشع، سُمّي نسبةً إلى كوري، ويُستخدم في بطاريات الفضاء",
      "Cn": "عنصر اصطناعي مشع، سُمّي نسبةً إلى كوبرنيكوس، اكتُشف عام 1996",
      "Co": "يُستخدم في المغناطيسات والبطاريات والأصباغ، أساسي لفيتامين ب12",
      "Cr": "معدن لامع، مقاوم للصدأ، يعطي الزمرد لونه الأخضر",
      "Cs": "معدن قلوي لين، يُستخدم في صناعة الساعات الذرية، ويتفاعل بشكل انفجاري مع الماء",
      "Cu": "يوصل الكهرباء، معدن قديم، يشكل البرونز مع القصدير",
      "Db": "عنصر اصطناعي مشع، سُمي على اسم دوبنا، اكتُشف عام 1967",
      "Ds": "عنصر اصطناعي مشع، سُمّي نسبةً إلى دارمشتات، اكتُشف عام 1994",
      "Dy": "يُقوّي المغناطيس، ويُستخدم في الليزر، ويمتص النيوترونات بكفاءة",
      "Er": "يُستخدم في الألياف البصرية والليزر وتلوين الزجاج باللون الوردي",
      "Es": "عنصر صناعي مشع، سُمّي نسبة لأينشتاين، نادر جداً.",
      "Eu": "يُستخدم في صناعة الفوسفور الأحمر، ويُستخدم في شاشات التلفزيون، وهو عنصر أرضي نادر",
      "F": "أكثر الهالوجينات تفاعلاً، يقوي الأسنان، يستخدم في المبردات",
      "Fe": "نواة الأرض، يبني الهيموغلوبين، يصد بسهولة بدون حماية",
      "Fl": "عنصر اصطناعي مشع، سُمّي نسبةً إلى مختبر فليروف، اكتُشف عام 1998",
      "Fm": "عنصر اصطناعي مشع، اكتُشف في حطام قنبلة هيدروجينية عام 1952",
      "Fr": "أندر الفلزات القلوية، مشع، يوجد بكميات ضئيلة جداً.",
      "Ga": "ينصهر قرب حرارة اليد، يُستخدم في أشباه الموصلات وLED.",
      "Gd": "يُستخدم كعامل تباين في التصوير بالرنين المغناطيسي، ويمتص النيوترونات، ويُستخدم في الإلكترونيات",
      "Ge": "شبه فلز مهم في الألياف البصرية وأشباه الموصلات.",
      "H": "أخف عنصر، يغذي النجوم، أساسي للماء والحياة",
      "He": "ثاني أخف عنصر، يملأ البالونات، اكتشف في طيف الشمس",
      "Hf": "مقاوم للحرارة، يمتص النيوترونات، يُستخدم في المفاعلات.",
      "Hg": "الزئبق سائل بدرجة الغرفة، سام، استُخدم في المقاييس.",
      "Ho": "أقوى عنصر مغناطيسي، ويُستخدم في الليزر، وهو من العناصر الأرضية النادرة",
      "Hs": "عنصر اصطناعي مشع، سُمي على اسم هيسه، اكتُشف عام 1984",
      "I": "عنصر غذائي أساسي، يمنع تضخم الغدة الدرقية، ويُستخدم في صناعة المطهرات والأدوية",
      "In": "معدن لين، يُستخدم في شاشات اللمس، اكتُشف في ألمانيا عام 1863",
      "Ir": "معدن نادر مقاوم للتآكل، يُستخدم في الشمعات والمحافزات.",
      "K": "عنصر غذائي ضروري، شديد التفاعل، يوجد في الموز والتربة",
      "Kr": "غاز نبيل يُستخدم في الإضاءة والليزر، خامل نسبياً.",
      "La": "يوجد في عدسات الكاميرات والمحفزات، وهو أول اللانثانيدات",
      "Li": "يزود البطاريات بالطاقة، يعالج اضطرابات المزاج، معدن قلوي نشط",
      "Lr": "عنصر اصطناعي مشع، سُمي على اسم لورانس، اكتُشف عام 1961",
      "Lu": "لانثانيد ثقيل، يُستخدم في كواشف PET وبعض العلاجات.",
      "Lv": "عنصر اصطناعي مشع، سُمّي نسبةً إلى ليفرمور، اكتُشف عام 2000",
      "Mc": "عنصر اصطناعي مشع، سُمّي نسبةً إلى موسكو، اكتُشف عام 2003",
      "Md": "عنصر اصطناعي مشع، سُمي على اسم مندليف، اكتُشف عام 1955",
      "Mg": "ضروري للعضلات، يحترق بشكل ساطع، يستخدم في الألعاب النارية والسبائك",
      "Mn": "يقوي الفولاذ، عنصر غذائي حيوي، يوجد في البطاريات والإنزيمات",
      "Mo": "عنصر غذائي أساسي، يقوي الفولاذ، يُستخدم في الزيوت والشحوم والمحفزات",
      "Mt": "عنصر اصطناعي مشع، سُمي على اسم ميتنر، اكتُشف عام 1982",
      "N": "78% من الهواء، يستخدم في الأسمدة، غاز خامل للحماية",
      "Na": "إلكتروليت ضروري، يتفاعل بعنف مع الماء، يحفظ الطعام",
      "Nb": "يقوي الفولاذ، مغناطيسات فائقة التوصيل، اكتُشف في معدن كونيتيكت",
      "Nd": "يُستخدم في المغناطيس القوي وسماعات الرأس والليزر، وهو ضروري للطاقة المتجددة",
      "Ne": "غاز نبيل، يضيء في اللافتات، خامل، اكتشف عام 1898",
      "Nh": "عنصر اصطناعي مشع، سُمّي نسبةً إلى اليابان، اكتُشف عام 2003",
      "Ni": "مقاوم للتآكل، يستخدم في النقود والفولاذ المقاوم للصدأ، وموجود في البطاريات القابلة لإعادة الشحن",
      "No": "عنصر اصطناعي مشع، سُمي على اسم نوبل، اكتُشف عام 1958",
      "Np": "عنصر مشع، وهو أول عنصر ما بعد اليورانيوم، ويُستخدم في كاشفات النيوترونات والأبحاث",
      "O": "أساسي للتنفس، يغذي الاحتراق، يشكل طبقة الأوزون الواقية",
      "Og": "عنصر اصطناعي مشع، سُمّي نسبةً إلى أوغانيسيان، اكتُشف عام 2002",
      "Os": "من أعلى العناصر كثافة، معدن نادر، يُستخدم في السبائك.",
      "P": "أساسي للحمض النووي، يلمع في الظلام، يُستخدم في الأسمدة",
      "Pa": "عنصر نادر ومشع، اكتُشف عام 1917، ويُستخدم في الأبحاث فقط",
      "Pb": "معدن ثقيل سام، يُستخدم في البطاريات ودرع الإشعاع.",
      "Pd": "يُستخدم في صناعة المجوهرات والإلكترونيات والمحولات الحفزية، ويمتص غاز الهيدروجين",
      "Pm": "عنصر مشع ونادر، يُستخدم في الطلاء المضيء والبطاريات النووية",
      "Po": "عنصر مشع شديد السمية، استُخدم في مصادر الحرارة.",
      "Pr": "عنصر أرضي نادر، يُستخدم في المغناطيس ومحركات الطائرات والزجاج الأخضر",
      "Pt": "معدن نفيس ومحفز قوي، يُستخدم في المجوهرات ومحولات العادم.",
      "Pu": "وقود نووي، ويُستخدم في الأسلحة، وهو عنصر مشع، اكتُشف عام 1940، وهو شديد السمية",
      "Ra": "عنصر مشع، استُخدم قديماً في الدهانات المضيئة، خطير.",
      "Rb": "فلز قلوي لين شديد التفاعل، يُستخدم في الأبحاث.",
      "Re": "نقطة انصهار عالية، يُستخدم في محركات النفاثات والسبائك.",
      "Rf": "عنصر اصطناعي مشع، سُمي على اسم روذرفورد، اكتُشف عام 1969",
      "Rg": "عنصر اصطناعي مشع، سُمّي نسبةً إلى رونتجين، اكتُشف عام 1994",
      "Rh": "لامع، نادر، يُستخدم في المحولات الحفازة، معدن ذو قيمة عالية",
      "Rn": "غاز نبيل مشع يتسرب من التربة، خطر على الصحة.",
      "Ru": "يقوي البلاتين، يُستخدم في الإلكترونيات، معدن انتقالي نادر",
      "S": "عنصر ذو رائحة، يقوي المطاط، يوجد في انبعاثات البراكين",
      "Sb": "يُستخدم في مثبطات اللهب والسبائك ومستحضرات التجميل، وهو سام عند الإفراط في استخدامه",
      "Sc": "يقوي سبائك الألومنيوم، نادر، يُستخدم في مكونات الطيران",
      "Se": "عنصر نزر ضروري للإنزيمات، يُستخدم في الخلايا الشمسية.",
      "Sg": "عنصر اصطناعي مشع، سُمي على اسم سيبورغ، اكتُشف عام 1974",
      "Si": "أساس الإلكترونيات، وفير في الرمل، يُكوّن مركبات قوية",
      "Sm": "يُستخدم في المغناطيس وعلاج السرطان، ويمتص النيوترونات في المفاعلات",
      "Sn": "معدن قديم، يمنع التآكل، يُستخدم في صناعة البرونز والعلب",
      "Sr": "يعطي الألعاب النارية لوناً أحمر، يوجد في العظام بكميات.",
      "Ta": "مقاوم للتآكل، يُستخدم في المكثفات والزرعات الطبية.",
      "Tb": "يُستخدم في الفوسفور الأخضر والمغناطيس، ويُساهم في استقرار خلايا الوقود",
      "Tc": "أول عنصر اصطناعي، يُستخدم في التصوير الطبي، مشع",
      "Te": "شبه فلز نادر، يُقوي السبائك، ويُستخدم في صناعة الألواح الشمسية",
      "Th": "مشع طبيعي، قد يُستخدم كوقود نووي بديل.",
      "Ti": "قوي وخفيف الوزن، مقاوم للتآكل، يُستخدم في الغرسات والطائرات",
      "Tl": "سام جداً، يُستخدم في الإلكترونيات وبعض كواشف الأشعة.",
      "Tm": "لانثانيد نادر، يُستخدم في الليزر وبعض الأجهزة الطبية.",
      "Ts": "عنصر اصطناعي مشع، سُمّي نسبةً إلى تينيسي، اكتُشف عام 2010",
      "U": "وقود نووي، مشع، اكتُشف عام 1789، ويُستخدم لتشغيل المفاعلات والأسلحة",
      "V": "يقوي الفولاذ، يُكوّن مركبات ملونة، يُستخدم في المحفزات",
      "W": "تنغستن شديد الصلابة، أعلى نقطة انصهار، فتائل المصابيح.",
      "Xe": "غاز نبيل، يُستخدم في صناعة المصابيح الأمامية والتخدير، اكتُشف عام 1898",
      "Y": "يُستخدم في الصمامات الثنائية الباعثة للضوء (LEDs)، يقوي السبائك، اكتُشف في محجر سويدي",
      "Yb": "لانثانيد يُستخدم في الليزر والذرات الباردة والساعات.",
      "Zn": "عنصر غذائي أساسي، يغلف الفولاذ، يعزز المناعة، يوجد في واقي الشمس",
      "Zr": "مقاوم للتآكل، يُستخدم في المفاعلات النووية، يوجد في الأحجار الكريمة"
    },
    
    // Category Labels
    atomicNo: "العدد الذري",
  }
};

export function t(key: string): string {
  const lang = localStorage.getItem("lang") || "ar";
  return translations[lang as 'en' | 'ar']?.[key] || key;
}
